# Generated by Django 3.1.5 on 2021-03-08 07:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_reciperegister'),
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegisterUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Customer_Name', models.CharField(blank=True, max_length=200, null=True)),
                ('Customer_Phone', models.IntegerField(blank=True, max_length=200, null=True)),
                ('Customer_Email', models.EmailField(blank=True, max_length=200, null=True)),
                ('Customer_Username', models.CharField(blank=True, max_length=200, null=True)),
                ('Customer_Password', models.CharField(blank=True, max_length=200, null=True)),
                ('Customer_Cpassword', models.CharField(blank=True, max_length=200, null=True)),
                ('Customer_Address', models.CharField(blank=True, max_length=200, null=True)),
                ('Customer_State', models.CharField(blank=True, max_length=200, null=True)),
                ('Customer_Country', models.CharField(blank=True, max_length=200, null=True)),
                ('Customer_Zip', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='cart',
            name='Productid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.productregister'),
        ),
    ]
