# Generated by Django 3.1.5 on 2021-03-12 04:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_auto_20210308_1230'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='Userid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='website.registeruser'),
        ),
        migrations.AlterField(
            model_name='registeruser',
            name='Customer_Phone',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
