# Generated by Django 3.1.5 on 2021-03-16 05:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_auto_20210312_1006'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Order_Name', models.CharField(blank=True, max_length=200, null=True)),
                ('Order_Phone', models.IntegerField(blank=True, null=True)),
                ('Order_Email', models.EmailField(blank=True, max_length=200, null=True)),
                ('Order_Address', models.CharField(blank=True, max_length=200, null=True)),
                ('Order_State', models.CharField(blank=True, max_length=200, null=True)),
                ('Order_Country', models.CharField(blank=True, max_length=200, null=True)),
                ('Order_Zip', models.CharField(blank=True, max_length=200, null=True)),
                ('Cartid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='website.cart')),
            ],
        ),
    ]
