# Generated by Django 3.1.5 on 2021-03-17 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='Status',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='Order_Uname',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='Status',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
