# Generated by Django 3.1.5 on 2021-03-18 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_auto_20210317_1043'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Message_Name', models.CharField(blank=True, max_length=200, null=True)),
                ('Message_Email', models.EmailField(blank=True, max_length=200, null=True)),
                ('Message_Subject', models.CharField(blank=True, max_length=200, null=True)),
                ('Message_Content', models.CharField(blank=True, max_length=250, null=True)),
            ],
        ),
    ]
