# Generated by Django 2.1.7 on 2021-04-21 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_Name', models.CharField(max_length=250)),
                ('task_priority', models.IntegerField()),
            ],
        ),
    ]
