# Generated by Django 2.1.7 on 2021-04-22 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='task_Date',
            field=models.DateField(default='1996-03-22'),
            preserve_default=False,
        ),
    ]
