# Generated by Django 3.1.5 on 2021-01-20 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ourapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='name',
            new_name='Name',
        ),
    ]
