# Generated by Django 3.1.5 on 2021-01-22 04:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ourapp', '0002_auto_20210120_1244'),
    ]

    operations = [
        migrations.CreateModel(
            name='Studentmark',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('studmark', models.IntegerField(blank=True, null=True)),
                ('stuentid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ourapp.student')),
            ],
        ),
    ]
