# Generated by Django 3.1.5 on 2021-01-28 06:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ourapp', '0005_auto_20210128_1111'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='Name',
            new_name='stud_Address',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='address',
            new_name='stud_Dist',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='email',
            new_name='stud_Email',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='dist',
            new_name='stud_Gender',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='gender',
            new_name='stud_Name',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='password',
            new_name='stud_Password',
        ),
    ]
