# Generated by Django 3.1.5 on 2021-02-04 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ourapp', '0006_auto_20210128_1153'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='stud_image',
            field=models.ImageField(blank=True, null=True, upload_to='studentimage'),
        ),
    ]
