# Generated by Django 3.1.5 on 2021-02-04 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ourapp', '0007_student_stud_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeedetails',
            name='emp_Image',
            field=models.ImageField(blank=True, null=True, upload_to='employeeimage'),
        ),
    ]
