# Generated by Django 2.1.7 on 2021-04-19 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RegistrationDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reg_Name', models.CharField(max_length=20)),
                ('reg_DOB', models.DateField()),
                ('reg_Address', models.CharField(max_length=20)),
                ('reg_Email', models.EmailField(max_length=20)),
                ('reg_Password', models.CharField(max_length=20)),
                ('reg_PNumber', models.CharField(max_length=20)),
                ('reg_Gender', models.CharField(max_length=20)),
            ],
        ),
    ]
