# Generated by Django 2.1.7 on 2021-04-19 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credentials', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registrationdetails',
            old_name='reg_PNumber',
            new_name='reg_CPassword',
        ),
        migrations.AlterField(
            model_name='registrationdetails',
            name='reg_DOB',
            field=models.CharField(max_length=20),
        ),
    ]
