# Generated by Django 3.1.5 on 2021-02-02 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RegistrationDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reg_Name', models.CharField(blank=True, max_length=20, null=True)),
                ('reg_DOB', models.DateField(blank=True, max_length=20, null=True)),
                ('reg_Address', models.CharField(blank=True, max_length=20, null=True)),
                ('reg_Email', models.EmailField(blank=True, max_length=20, null=True)),
                ('reg_Password', models.CharField(blank=True, max_length=20, null=True)),
                ('reg_PNumber', models.CharField(blank=True, max_length=20, null=True)),
                ('reg_Gender', models.CharField(blank=True, max_length=20, null=True)),
                ('reg_State', models.CharField(blank=True, max_length=20, null=True)),
                ('reg_District', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
    ]
