# Generated by Django 3.1.5 on 2021-02-02 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrationdetails',
            name='reg_DOB',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
