# Generated by Django 3.1.5 on 2021-02-08 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryRegister',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Category_Name', models.CharField(blank=True, max_length=200, null=True)),
                ('Category_Image', models.ImageField(blank=True, null=True, upload_to='categoryimage')),
            ],
        ),
    ]
