# Generated by Django 3.1.5 on 2021-02-10 06:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_productregister'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productregister',
            name='Product_Category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.categoryregister'),
        ),
    ]
