# Generated by Django 3.1.5 on 2021-02-10 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_auto_20210210_1142'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productregister',
            name='Product_Category',
        ),
    ]
