# Generated by Django 3.1.5 on 2021-02-10 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_remove_productregister_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='productregister',
            name='Product_Category',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
