# Generated by Django 3.1.5 on 2021-02-10 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_productregister_product_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecipeRegister',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Recipe_Name', models.CharField(blank=True, max_length=200, null=True)),
                ('Recipe_Image', models.ImageField(blank=True, null=True, upload_to='recipeimage')),
                ('Recipe_Ingredient', models.CharField(blank=True, max_length=200, null=True)),
                ('Recipe_Description', models.CharField(blank=True, max_length=200, null=True)),
                ('Recipe_Time', models.CharField(blank=True, max_length=200, null=True)),
                ('Recipe_Calorie', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
    ]
